cache:
    paths:
      - node_modules/
      - .yarn

stages:
    - build
    - deploy

staging_build:
    variables:
        ENVIRONMENT: staging
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc staging."
        - cp ./public/config.staging.js ./public/config.js
        - docker-compose build
        - docker-compose push

staging_deploy:
    variables:
        ENVIRONMENT: staging
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcstaging
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc staging."
        - docker rm -f ffc_frontend || true
        - docker-compose pull
        - docker-compose up -d

production_build:
    variables:
        ENVIRONMENT: production
    stage: build
    tags:
        - builder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc production."
        - cp ./public/config.production.js ./public/config.js
        - docker-compose build
        - docker-compose push

production_deploy:
    variables:
        ENVIRONMENT: production
    stage: deploy
    when: manual
    tags:
        - ffcproduction
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc production."
        - docker rm -f ffc_frontend || true
        - docker-compose pull
        - docker-compose up -d
