cache:
    paths:
      - node_modules/
      - .yarn

stages:
    - build
    - deploy

staging_build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc staging."
        - docker build -t jimber/freeflowconnect:staging-$CI_COMMIT_TAG .
        - dockdocker run -dit --name=ffc_backend_redis --network=ffc_network redis:alpine

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcstaging
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc staging."
        - docker pull jimber/freeflowconnect:staging-$CI_COMMIT_TAG
        - docker rm -f ffc_frontend || true
        - docker run -d -it --name=ffc_frontend --network=ffc_network -p 8080:80 jimber/freeflowconnect:staging-$CI_COMMIT_TAG

production_build:
    stage: build
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc production."
        - docker build -t jimber/freeflowconnect:production-$CI_COMMIT_TAG .
        - docker push jimber/freeflowconnect:production-$CI_COMMIT_TAG

production_deploy:
    stage: deploy
    when: manual
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcproduction
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc production."
        - docker pull jimber/freeflowconnect:production-$CI_COMMIT_TAG
        - docker rm -f ffc_frontend || true
        - docker run -d -it --name=ffc_frontend --network=ffc_network -p 8080:80 jimber/freeflowconnect:production-$CI_COMMIT_TAG
